### ISSUE TITLE
props not passed to SmoothieChart

### ISSUE THREAD

**Issue by mseiwald** [cinderblock/react-smoothie#1]
The following grid options object is not passed to the SmoothieChart constructor. Am I doing something wrong?

    render: function() {
      return <SmoothieComponent ref="chart" width="150" height="25" grid={{ strokeStyle:'rgb(255, 0, 0)', fillStyle:'rgb(60, 0, 0)',
            lineWidth: 1, millisPerLine: 250, verticalSections: 6 }} />;
    },

**Comment by cinderblock** [comment]
I recently realized I was incorrectly using the spread operator when creating a new instance of a SmoothieChart. I have just fixed this in v0.1.0

Please try that version.

**Comment by cinderblock** [comment]
Closing because I believe this is fixed
