### ISSUE TITLE
Displaying timestamps

### ISSUE THREAD

**Issue by hodn** [cinderblock/react-smoothie#3]
Is it possible to pass the prop to display timestamps?

**timestampFormatter:SmoothieChart.timeFormatter** in the Smoothie Charts Builder

**Comment by cinderblock** [comment]
Hmm. I'm not sure why that wouldn't work. What have you tried?

----

The `props` are just passed to `new Smoothie(props)` basically. Specifically:
https://github.com/cinderblock/react-smoothie/blob/28372380a96e29ba695a6bc745009257427acf8a/SmoothieComponent.tsx#L133
https://github.com/cinderblock/react-smoothie/blob/28372380a96e29ba695a6bc745009257427acf8a/SmoothieComponent.tsx#L163

----

This works for me:

```TypeScript
<SmoothieComponent timestampFormatter={date => 'Foobar'} />
```
![image](https://user-images.githubusercontent.com/419955/59335910-5df64a00-8cb2-11e9-986e-0942aacca23d.png)

**Comment by hodn** [comment]
Alright, it is also working for me this way. Thank you very much.
