### ISSUE TITLE
Chart pause

### ISSUE THREAD

**Issue by maxiy01** [cinderblock/react-smoothie#6]
Hello, sorry for probably dumb question, but:
Is it possible to pause chart running?

**Comment by cinderblock** [comment]
Hello! There is never a dumb question.

This library uses charting by [https://github.com/joewalnes/smoothie](Smoothie Charts). So it supports whatever they support basically.

It looks like yes, there is an option to do what you want: `nonRealtimeData` as of Smoothie 1.34 (we're on 1.35) where smoothie uses the last pushed data as the "current" time.

However, I see that I'm not exposing that this option is available and if you try to use it correctly in TypeScript, I expect you'll get a compile time error. I probably just need to push a new version of react-smoothie that properly exposes that type.
