### ISSUE TITLE
Series can't be added dynamically using the prop API

### ISSUE THREAD

**Issue by Guichaguri** [cinderblock/react-smoothie#8]
The component has to be mounted with all series in place. If I add a new one dynamically, it will not show up, the ref API works as expected. Is this behavior intended?

**Comment by cinderblock** [comment]
No, that is not intended. I'll need to add some code to handle this case I think.

**Comment by cinderblock** [comment]
@Guichaguri I just pushed a version that I think should handle the problem. I haven't had a chance to test it however. Can you try it?

**Comment by Guichaguri** [comment]
Works as expected. Thank you!

**Comment by cinderblock** [comment]
I'll push to npm
